# Generated by Django 6.0.6 on 2026-07-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contactrequest_status_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("finished", "Finished"),
                    ("confirmed", "Confirmed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
