# Generated by Django 6.0.6 on 2026-07-21 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_contactrequest_status"),
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactRequest",
            new_name="Reservation",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="request",
            new_name="reservation",
        ),
        migrations.RemoveField(
            model_name="message",
            name="request",
        ),
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
