# Generated by Django 6.0.6 on 2026-06-28 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetOwnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetSitterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cin", models.CharField(max_length=20, unique=True)),
                ("cin_verified", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True)),
                (
                    "price_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("accepts_dogs", models.BooleanField(default=True)),
                ("accepts_cats", models.BooleanField(default=True)),
                ("accepts_other", models.BooleanField(default=False)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sitter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
