# Generated by Django 6.0.6 on 2026-07-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_petownerprofile_petsitterprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="petsitterprofile",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="petsitterprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="petsitterprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="completed_bookings_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
