# Generated by Django 6.0.6 on 2026-07-21 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_petsitterprofile_is_premium_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petsitterprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="completed_bookings_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="review_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verified",
        ),
        migrations.CreateModel(
            name="SitterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "price_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("accepts_dogs", models.BooleanField(default=True)),
                ("accepts_cats", models.BooleanField(default=True)),
                ("accepts_other", models.BooleanField(default=False)),
                ("rating", models.FloatField(default=0.0)),
                ("is_premium", models.BooleanField(default=False)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("completed_bookings_count", models.PositiveIntegerField(default=0)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sitter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SitterPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="sitters/")),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.sitterprofile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PetOwnerProfile",
        ),
        migrations.DeleteModel(
            name="PetSitterProfile",
        ),
    ]
